### PR TITLE
fix: configs not working for the deprecated pyls

### LINKED ISSUE #385: Failing to disable pycodestyle
I just started with a clean & fresh Atom configuration and installed `ide-python`. I am failing to disable `pycodestyle`. No matter what I do, I get warnings from it in both the source code and the linter panel.

Intended behavior: Enabling `ide-python` with `flake8`, `PyFlakes` and `pycodestyle` explicitly disabled - no warnings from `pycodestyle`.

Actual behavior: Enabling `ide-python`, disabling *all* Python language server plugins - still warnings from `pycodestyle`.

"Workaround": Disabling `ide-python` altogether.

---

- atom: 1.58.0
- ide-python: 1.9.5
- os: Linux x86_64

### PR DESCRIPTION
**Pull request by aminya**
Fixes #385

### CODE REVIEW

File: lib/main.js [hunk 1]
```diff
@@ -45,8 +45,21 @@ class PythonLanguageClient extends AutoLanguageClient {
     return "ide-python"
   }
 
+  getPyLs() {
+    if (this.pyls === undefined) {
+      let pyls = atom.config.get("ide-python.pyls") || "pylsp"
+      // check if it exists
+      if (whichSync(pyls, { nothrow: true }) === null) {
+        pyls = "pyls"
```
Comment (k2d222) [inline lib/main.js:53]: This should be like `pyls = (pyls === "pylsp") ? "pyls" : "pylsp"` so if  `ide-python.pyls` is not the default it falls back to `pylsp` instead of `pyls`. 
Maybe check further for pylsp and fallback to pyls : ide-python.pyls --> pylsp --> pyls

Comment (aminya) [reply lib/main.js:53]:
```suggestion
		// use the other one if it doesn't exist
        pyls = (pyls === "pylsp") ? "pyls" : "pylsp"
```

**Comment by aminya** [comment]
We should be good now
